DELIMITER //

CREATE TRIGGER actualiza_existencias
AFTER INSERT ON DET_VENTA
FOR EACH ROW
BEGIN
    DECLARE exits  NUMERIC(3);
    DECLARE falt   NUMERIC(3);

    SELECT EXISTENCIA
    INTO   exits
    FROM   PRODUCTO
    WHERE  CVE_PROD = NEW.CVE_PROD;

    IF exits >= NEW.CANTIDAD THEN

        UPDATE PRODUCTO
        SET    EXISTENCIA = EXISTENCIA - NEW.CANTIDAD
        WHERE  CVE_PROD = NEW.CVE_PROD;

    ELSE

        SET falt = NEW.CANTIDAD - exits;

        UPDATE PRODUCTO
        SET    EXISTENCIA = 0
        WHERE  CVE_PROD = NEW.CVE_PROD;

        INSERT INTO BACKORDER (NUM_VENTA, CVE_PROD, CANTIDAD)
        VALUES (NEW.NUM_VENTA, NEW.CVE_PROD, falt);

    END IF;
END//

